# 九、评价模型
在实际应用中, 经常遇到有关综合评价问题, 如医疗质量和环境质量的综合评价等. 所谓综合评价是指根据一个系统同时受到多种因素影响的特点, 在综合考察多个有关因素, 依据多个相关指标对系统进行总评价的方法. 目前, 已经提出了很多综合评价的方法, 如TOPSIS方法、层次分析法、模糊综合评价法、灰色系统法等. 这些方法各具特色也各有利弊, 由于受到多方面因素的影响, 如何使评价更准确和更科学, 一直是人们不断研究的课题. 本章介绍一些常用的评价方法的基本原理、主要步骤以及它们在实际中的应用.


## 9.1 综合评价的基本理论和数据预处理
### 9.1.1 综合评价的基本概念
一般地, 一个综合评价问题是由评价对象、评价指标、权重系数、综合评价模型和评价者五个基本要素组成.

1.评价对象
评价对象就是综合评价问题中所研究的对象, 或称为系统. 通常情况下, 在一个问题中评价对象是属于同一类的, 且个数要大于1, 不妨假设一个综合评价问题中有$n$个评价对象, 分别记为$S_1, S_2, \cdots, S_n(n>1)$.

2.评价指标
评价指标是反映评价对象的运行 (或发展) 状况的基本要素. 通常的问题都是有多项指标构成, 每一项指标都是从不同的侧面刻画系统所具有某种特征大小的一个度量.
一个综合评价问题的评价指标一般可用一个向量 $x$ 表示, 称为评价指标向量, 其中每一个分量就是从一个侧面反映系统的状态; 也称为综合评价的指标体系. 在建立评价指标体系时, 一般应遵循以下原则: (1) 系统性; (2) 独立性; (3) 可 观测性; (4) 科学性; (5) 可比性. 不失一般性, 设系统有 $m$ 个评价指标, 分别记为 $x_1, x_2, \cdots, x_m(m>1)$, 即评价指标向量为 $\boldsymbol{x}=\left[x_1, x_2, \cdots, x_m\right]$.

3.权重系数
每一个综合评价问题都有相应的评价目的, 针对某种评价目的, 各评价指标之间的相对重要性是不同的, 评价指标之间的这种相对重要性的大小, 可用权重系数来刻画. 如果用 $w_j(j=1,2, \cdots, m)$ 来表示评价指标 $x_j$ 的权重系数, 一般应满足
$$
w_j \geqslant 0, \quad j=1,2, \cdots, m \text { 且 } \sum_{j=1}^m w_j=1 .
$$
当各评价对象和评价指标值都确定以后, 综合评价结果就依赖于权重系数的取值了, 即权重系数确定的合理与否, 直接关系到综合评价结果的可信度, 甚至影响到最后决策的正确性. 因此, 权重系数的确定要特别谨慎, 应按一定的方法和原则来确定.

4.综合评价模型
对于多指标 (或多因素) 的综合评价问题, 就是要通过建立一定的数学模型将 多个评价指标值综合成为一个整体的综合评价值, 作为综合评价的依据, 从而得到相应的评价结果.
不妨假设第 $i(i=1,2, \cdots, n)$ 个评价对象的 $m$ 个评价指标值构成的向量为 $\boldsymbol{a}_i=\left[a_{i 1}, a_{i 2}, \cdots, a_{i m}\right]$, 指标权重向量为 $\boldsymbol{w}=\left[w_1, w_2, \cdots, w_m\right]$, 由此构造综合评价模型
$$
y=f(\boldsymbol{x}, \boldsymbol{w}),
$$
并计算出第 $i$ 个评价对象的综合评价值 $b_i=f\left(\boldsymbol{a}_i, \boldsymbol{w}\right)$, 根据 $b_i(i=1,2, \cdots, n)$ 值的大小, 将这 $n$ 个评价对象进行排序或分类, 即得到综合评价结果.

5.评价者
评价者是直接参与评价的人, 可以是一个人, 也可以是一个团体. 对于评价目的的选择、评价指标体系确定、权重系数的确定和评价模型的建立都与评价者有关. 因此, 评价者在评价过程中的作用是不可小视的.

### 9.1.2 综合评价体系的构建
综合评价过程包括评价指标体系的建立、评价指标的预处理、指标权重的确定和评价模型的选择等重要环节. 其中评价指标体系的构建与评价指标的篮选是综合评价的重要基础, 也是做好综合评价的保证.

1.评价指标和评价指标体系
所谓指标就是用来评价系统的参量. 例如, 在校学生规模、教育质量、师资结构、科研水平等, 可以作为评价高等院校综合水平的主要指标. 一般来说, 任何一个 指标都反映和刻画事物的一个侧面.
从指标值的特征来看, 指标可以分为定性指标和定量指标. 定性指标是用定性的语言作为指标描述值. 例如, 旅游景区质量等级有 $5 \mathrm{~A}, 4 \mathrm{~A}, 3 \mathrm{~A}, 2 \mathrm{~A}$ 和 $1 \mathrm{~A}$ 之分, 则旅游景区质量等级是定性指标, 而景区年旅客接待量、门票收入等就是定量指标.
从指标值的变化对评价目的的影响来看, 可以将指标分为以下四类:
(1) 极大型指标 (又称为效益型指标) 是指标值越大越好的指标;
(2) 极小型指标 (又称为成本型指标) 是指标值越小越好的指标;
(3) 居中型指标是指标值既不是越大越好, 也不是越小越好, 而是适中为最好 的指标;
(4) 区间型指标是指标值取在某个区间内为最好的指标.
例如, 在评价企业的经济效益时, 利润作为指标, 其值越大, 经济效益就越好, 这就是效益型指标; 而管理费用作为指标, 其值越小, 经济效益就越好, 所以管理费用是成本型指标. 投标报价既不能太高又不能太低, 其值的变化范围一般是 $(90 \%$, $105 \%) \times$ 标的价, 超过此范围的都将被淘汰, 因此投标报价为区间型指标. 投标工期既不能太长又不能太短, 就是居中型指标.
在实际中, 不论按什么方式对指标进行分类, 不同类型的指标可以通过相应的数学方法进行相互转换. 所谓评价指标体系就是由众多评价指标组成的指标系统. 在指标体系中, 每个指标对系统的某种特征进行度量, 共同形成对系统的完整刻画.

2.评价指标的笼选方法
笑选评价指标, 要根据综合评价的目的, 针对具体的评价对象、评价内容收集有关指标信息, 采用适当的管选方法对指标进行笄选, 合理地选取主要指标, 剔除次要指标, 以简化评价指标体系. 常用的评价指标笄选方法主要有专家调研法、最小均方差法、极大极小离差法等.
1)专家调研法 (Delphi 法)
评价者根据评价目标和评价对象的特征, 首先设计出一系列指标的调查表, 向若干专家咨询和征求对指标的意见, 然后进行统计处理, 并反馈意见处理结果, 经过几轮咨询后, 当专家意见趋于集中时, 将专家意见集中的指标作为评价指标, 从而建立起综合评价指标体系.
2)最小均方差法
对于 $n$ 个评价对象 $S_1, S_2, \cdots, S_n$, 每个评价对象有 $m$ 个指标, 其观测值分 别为
$$
a_{i j} \quad(i=1,2, \cdots, n ; j=1,2, \cdots, m) .
$$
如果 $n$ 个评价对象关于某项指标的观测值都差不多, 那么不管这个评价指标重要与否, 对于这 $n$ 个评价对象的评价结果所起的作用将是很小的. 因此, 在评价过程中就可以删除这样的评价指标.

最小均方差法的筞选过程如下:
(1) 求出第 $j$ 项指标的平均值和均方差
$$
\mu_j=\frac{1}{n} \sum_{i=1}^n a_{i j}, \quad s_j=\sqrt{\frac{1}{n} \sum_{i=1}^n\left(a_{i j}-\mu_j\right)^2}, \quad j=1,2, \cdots, m .
$$
(2) 求出最小均方差
$$
s_{j_0}=\min _{1 \leqslant j \leqslant m}\left\{s_j\right\} .
$$
(3) 如果最小均方差 $s_{j_0} \approx 0$, 则可删除与 $s_{j_0}$ 对应的指标 $x_{j_0}$. 考察完所有指标, 即可得到最终的评价指标体系.
最小均方差法只考虑了指标的差异程度, 容易将重要的指标删除.
3) 极大极小离差法
对于 $n$ 个评价对象 $S_1, S_2, \cdots, S_n$, 每个评价对象有 $m$ 个指标, 其观测值分别为
$$
a_{i j} \quad(i=1,2, \cdots, n ; j=1,2, \cdots, m) .
$$
极大极小离差法的答选过程如下:
(1) 求出第 $j$ 项指标的最大离差
$$
d_j=\max _{1 \leqslant i<k \leqslant n}\left\{\left|a_{i j}-a_{k j}\right|\right\}, \quad j=1,2, \cdots, m .
$$
(2) 求出最小离差
$$
d_{j_0}=\min _{1 \leqslant j \leqslant m}\left\{d_j\right\} .
$$
(3) 如果最小离差 $d_{j_0} \approx 0$, 则可删除与 $d_{j_0}$ 对应的指标 $x_{j_0}$, 考察完所有指标, 即可得到最终的评价指标体系.
常用的评价指标笑选方法还有条件广义方差极小法、极大不相关法等, 详细介绍可参阅相关资料.

### 9.1.3 评价指标的预处理方法
一般情况下, 在综合评价指标中, 各指标值可能属于不同类型、不同单位或不同数量级, 从而使得各指标之间存在着不可公度性, 给综合评价带来了诸多不便. 为了尽可能地反映实际情况, 消除由于各项指标间的这些差别带来的影响, 避免出现不合理的评价结果, 就需要对评价指标进行一定的预处理, 包括对指标的一致化处理和无量纲化处理.

1.指标的一致化处理
所谓一致化处理就是将评价指标的类型进行统一. 一般来说, 在评价指标体系中, 可能会同时存在极大型指标、极小型指标、居中型指标和区间型指标, 它们都具有不同的特点. 若指标体系中存在不同类型的指标, 必须在综合评价之前将评价指标的类型做一致化处理. 例如, 将各类指标都转化为极大型指标或极小型指标. 一般的做法是将非极大型指标转化为极大型指标. 但是, 在不同的指标权重确定方法和评价模型中, 指标一致化处理也有差异.

1)极小型指标化为极大型指标
对极小型指标 $x_j$, 将其转化为极大型指标时, 只需对指标 $x_j$ 取倒数:
$$
x_j^{\prime}=\frac{1}{x_j}
$$
或做平移变换:
$$
x_j^{\prime}=M_j-x_j,
$$
其中 $M_j=\max _{1 \leqslant i \leqslant n}\left\{a_{i j}\right\}$, 即 $n$ 个评价对象第 $j$ 项指标值 $a_{i j}$ 最大者.

2)居中型指标化为极大型指标
对居中型指标 $x_j$, 令 $M_j=\max _{1 \leqslant i \leqslant n}\left\{a_{i j}\right\}, m_j=\min _{1 \leqslant i \leqslant n}\left\{a_{i j}\right\}$,取
$$
x_j^{\prime}= \begin{cases}\frac{2\left(x_j-m_j\right)}{M_j-m_j}, & m_j \leqslant x_j \leqslant \frac{M_j+m_j}{2}, \\ \frac{2\left(M_j-x_j\right)}{M_j-m_j}, & \frac{M_j+m_j}{2}<x_j \leqslant M_j,\end{cases}
$$
就可以将 $x_j$ 转化为极大型指标.

3)区间型指标化为极大型指标
对区间型指标 $x_j, x_j$ 取值属于 $\left[b_j^{(1)}, b_j^{(2)}\right]$ 时为最好, 指标值离该区间越远就越差. 令 $M_j=\max _{1 \leqslant i \leqslant n}\left\{a_{i j}\right\}, m_j=\min _{1 \leqslant i \leqslant n}\left\{a_{i j}\right\}, c_j=\max \left\{b_j^{(1)}-m_j, M_j-b_j^{(2)}\right\}$, 取
$$
x_j^{\prime}= \begin{cases}1-\frac{b_j^{(1)}-x_j}{c_j}, & x_j<b_j^{(1)}, \\ 1, & b_j^{(1)} \leqslant x_j \leqslant b_j^{(2)}, \\ 1-\frac{x_j-b_j^{(2)}}{c_j}, & x_j>b_j^{(2)},\end{cases}
$$
就可以将区间型指标 $x_j$ 转化为极大型指标.
类似地, 通过适当的数学变换, 也可以将极大型指标、居中型指标转化为极小型指标.

2.指标的无量纲化处理
所谓无量纲化, 也称为指标的规范化, 是通过数学变换来消除原始指标的单位及其数值数量级影响的过程, 因此, 就有指标的实际值和评价值之分. 一般地, 将指标无量纲化处理以后的值称为指标评价值. 无量纲化过程就是将指标实际值转化为指标评价值的过程.
对于 $n$ 个评价对象 $S_1, S_2, \cdots, S_n$, 每个评价对象有 $m$ 个指标, 其观测值分别为
$$
a_{i j} \quad(i=1,2, \cdots, n ; j=1,2, \cdots, m) .
$$

1)标准样本变换法
令
$$
a_{i j}^*=\frac{a_{i j}-\mu_j}{s_j} \quad(1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m),
$$
其中样本均值 $\mu_j=\frac{1}{n} \sum_{i=1}^n a_{i j}$, 样本标准差 $s_j=\sqrt{\frac{1}{n} \sum_{i=1}^n\left(a_{i j}-\mu_j\right)^2}$.
注9.1 对于要求评价指标值 $a_{i j}^*>0$ 的评价方法, 如熵权法和几何加权平均法等, 该数据处理方法不适用.

2)比例变换法
对于极大型指标, 令
$$
a_{i j}^*=\frac{a_{i j}}{\max _{1 \leqslant i \leqslant n} a_{i j}} \quad\left(\max _{1 \leqslant i \leqslant n} a_{i j} \neq 0,1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m\right) .
$$
对极小型指标, 令
$$
a_{i j}^*=\frac{\min _{1 \leqslant i \leqslant n} a_{i j}}{a_{i j}} \quad(1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m)
$$
或
$$
a_{i j}^*=1-\frac{a_{i j}}{\max _{1 \leqslant i \leqslant n} a_{i j}} \quad\left(\max _{1 \leqslant i \leqslant n} a_{i j} \neq 0,1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m\right) .
$$
该方法的优点是这些变换前后的属性值成比例. 但对任一指标来说, 变换后的 $a_{i j}^*=1$ 和 $a_{i j}^*=0$ 不一定同时出现.

3)向量归一化法
对于极大型指标, 令
$$
a_{i j}^*=\frac{a_{i j}}{\sqrt{\sum_{i=1}^n a_{i j}^2}}(i=1,2, \cdots, n, 1 \leqslant j \leqslant m) .
$$
对于极小型指标, 令
$$
a_{i j}^*=1-\frac{a_{i j}}{\sqrt{\sum_{i=1}^n a_{i j}^2}}(i=1,2, \cdots, n, 1 \leqslant j \leqslant m) .
$$

4)极差变换法
对于极大型指标, 令
$$
a_{i j}^*=\frac{a_{i j}-\min _{1 \leqslant i \leqslant n} a_{i j}}{\max _{1 \leqslant i \leqslant n} a_{i j}-\min _{1 \leqslant i \leqslant n} a_{i j}} \quad(1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m) .
$$
对于极小型指标, 令
$$
a_{i j}^*=\frac{\max _{1 \leqslant i \leqslant n} a_{i j}-a_{i j}}{\max _{1 \leqslant i \leqslant n} a_{i j}-\min _{1 \leqslant i \leqslant n} a_{i j}} \quad(1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m) .
$$
其特点为经过极差变换后, 均有 $0 \leqslant a_{i j}^* \leqslant 1$, 且最优指标值 $a_{i j}^*=1$, 最劣指标值 $a_{i j}^*=0$. 该方法的缺点是变换前后的各指标值不成比例.

5)功效系数法
令
$$
a_{i j}^*=c+\frac{a_{i j}-\min _{1 \leqslant i \leqslant n} a_{i j}}{\max _{1 \leqslant i \leqslant n} a_{i j}-\min _{1 \leqslant i \leqslant n} a_{i j}} \times d \quad(1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m),
$$
其中 $c, d$ 均为确定的常数, $c$ 表示 “平移量”, 表示指标实际基础值; $d$ 表示 “旋转 量”, 即表示 “放大” 或 “缩小” 倍数, 则 $a_{i j}^* \in[c, c+d]$.
通常取 $c=60, d=40$, 即
$$
a_{i j}^*=60+\frac{a_{i j}-\min _{1 \leqslant i \leqslant n} a_{i j}}{\max _{1 \leqslant i \leqslant n} a_{i j}-\min _{1 \leqslant i \leqslant n} a_{i j}} \times 40 \quad(1 \leqslant i \leqslant n, 1 \leqslant j \leqslant m),
$$
则 $a_{i j}^*$ 实际基础值为 60 , 最大值为 100 , 即 $a_{i j}^* \in[60,100]$.

3.定性指标的定量化
在综合评价工作中, 有些评价指标是定性指标, 即只给出定性的描述, 例如, 质量很好、性能一般、可靠性高等. 对于这些指标, 在进行综合评价时, 必须先通过适当的方式进行赋值, 使其量化. 一般来说, 对于指标最优值可赋值 1 , 对于指标最劣值可赋值 0. 对极大型和极小型定性指标常按以下方式赋值.

1)极大型定性指标量化方法
对于极大型定性指标而言, 如果指标能够分为很低、低、一般、高和很高五个等级, 则可以分别取量化值为 $0,0.3,0.5,0.7,1$, 对应关系如表 9.1 所示. 介于两个等级之间的可以取两个分值之间的适当数值作为量化值.
表 9.1 极大型定性指标对应量化值
\begin{array}{cccccc}
\hline 等级 & 很低 & 低 & 一般 & 高 & 很高 \\
\hline 量化值 & 0 & 0.3 & 0.5 & 0.7 & 1 \\
\hline
\end{array}

2)极小型定性指标量化方法
对于极小型定性指标而言, 如果指标能够分为很高、高、一般、低和很低五个等级, 则可以分别取量化值为 $0,0.3,0.5,0.7,1$, 对应关系如表 9.2 所示. 介于两个等级之间的可以取两个分值之间的适当数值作为量化值.
表 9.2 极小型定性指标对应量化值
\begin{array}{cccccc}
\hline 等级 & 很高 & 高 & 一般 & 低 & 很低 \\
\hline 量化值 & 0 & 0.3 & 0.5 & 0.7 & 1 \\
\hline
\end{array}

### 9.1.4 评价指标预处理示例
下面考虑一个战斗机性能的综合评价问题.

例 战斗机的性能指标主要包括最大速度、飞行半径、最大负载、隐身性能、垂直起降性能、可靠性、灵敏度等指标和相关费用. 综合各方面因素与条件, 忽略了隐身性能和垂直起降性能, 只考虑余下的六项指标, 请就 $A_1, A_2, A_3$ 和 $A_4$ 四种类型战斗机的性能进行评价分析, 其六项指标值如表 9.3 所示.
表9.3 四种战斗机性能指标数据
$$
\begin{array}{ccccccc}
\hline & 最大速度/马赫 & 飞行半径 / km & 最大负载/磅 & 费用/美元 & 可靠性 & 灵敏度 \\
\hline
A_1 & 2.0 & 1500 & 20000 & 5500000 & 一般 & 很高 \\
A_2 & 2.5 & 2700 & 18000 & 6500000 & 低 & 一般 \\
A_3 & 1.8 & 2000 & 21000 & 4500000 & 高 & 高 \\
A_4 & 2.2 & 1800 & 20000 & 5000000 & 一般 & 一般 \\
\hline
\end{array}
$$
下面对这些指标数据进行预处理.
假设将六项指标依次记为 $x_1, x_2, \cdots, x_6$, 首先将 $x_5$ 和 $x_6$ 两项定性指标进行量化处理, 量化后的数据如表 9.4 所示.
数值型指标中 $x_1, x_2, x_3$ 为极大型指标, 费用 $x_4$ 为极小型指标. 下面给出几种处理方式的结果. 采用向量归一化法对各指标进行标准化处理, 可得评价矩阵
$$
\boldsymbol{R}_1=\left[\begin{array}{llllll}
0.4671 & 0.3662 & 0.5056 & 0.4931 & 0.4811 & 0.7089 \\
0.5839 & 0.6591 & 0.4550 & 0.4010 & 0.2887 & 0.3544 \\
0.4204 & 0.4882 & 0.5308 & 0.5853 & 0.6736 & 0.4962 \\
0.5139 & 0.4394 & 0.5056 & 0.5392 & 0.4811 & 0.3544
\end{array}\right]
$$
采用比例变换法对各数值型指标进行标准化处理, 可得评价矩阵
$$
\boldsymbol{R}_2=\left[\begin{array}{cccccc}
0.8 & 0.5556 & 0.9524 & 0.8182 & 0.7143 & 1 \\
1 & 1 & 0.8571 & 0.6923 & 0.4286 & 0.5 \\
0.72 & 0.7407 & 1 & 1 & 1 & 0.7 \\
0.88 & 0.6667 & 0.9524 & 0.9 & 0.7143 & 0.5
\end{array}\right] .
$$
采用极差变换法对各数值型指标进行标准化处理, 可得评价矩阵
$$
\boldsymbol{R}_3=\left[\begin{array}{cccccc}
0.2857 & 0 & 0.6667 & 0.5 & 0.5 & 1 \\
1 & 1 & 0 & 0 & 0 & 0 \\
0 & 0.4167 & 1 & 1 & 1 & 0.4 \\
0.5714 & 0.25 & 0.75 & 0.75 & 0.5 & 0
\end{array}\right] .
$$
表 9.4 可靠性与灵敏度指标量化值
\begin{array}{ccccccc}
\hline
& 最大速度 x_1 & 飞行半径 x_2 & 最大负载 x_3 & 费用 x_4 & 可靠性 x_5 & 灵敏度 x_6 \\
\hline
A_1 & 2.0 & 1500 & 20000 & 5500000 & 0.5 & 1 \\
A_2 & 2.5 & 2700 & 18000 & 6500000 & 0.3 & 0.5 \\
A_3 & 1.8 & 2000 & 21000 & 4500000 & 0.7 & 0.7 \\
A_4 & 2.2 & 1800 & 20000 & 5000000 & 0.5 & 0.5 \\
\hline
\end{array}

In [ ]:
import numpy as np
import pandas as pd
import os

a = np.loadtxt(os.path.join("data", "Pdata9_1_1.txt"))
R1 = a.copy()
R2 = a.copy()
R3 = a.copy()  #初始化

#注意R1=a,它们的内存地址一样，R1改变时，a也改变
for j in [0, 1, 2, 4, 5]:
    R1[:, j] = R1[:, j]/np.linalg.norm(R1[:, j]) #向量归一化
    R2[:, j] = R1[:, j]/max(R1[:, j])     #比例变换
    R3[:, j] = (R3[:, j]-min(R3[:, j]))/(max(R3[:, j])-min(R3[:, j]))
R1[:, 3] = 1-R1[:, 3]/np.linalg.norm(R1[:, 3])
R2[:, 3] = min(R2[:, 3])/R2[:, 3]
R3[:, 3] = (max(R3[:, 3])-R3[:, 3])/(max(R3[:, 3])-min(R3[:, 3]))
np.savetxt("data/Pdata9_1_2.txt", R1) #把数据写入文本文件，供下面使用
np.savetxt("data/Pdata9_1_3.txt", R2)
np.savetxt("data/Pdata9_1_4.txt", R3)
DR1 = pd.DataFrame(R1)  #生成DataFrame类型数据
DR2 = pd.DataFrame(R2)
DR3 = pd.DataFrame(R3)
f = pd.ExcelWriter('data/Pdata9_1_5.xlsx')  #创建文件对象
# DR1.to_excel(f, "sheet1")  #把DR1写入Excel文件1号表单中,方便做表
# DR2.to_excel(f, "sheet2")
# DR3.to_excel(f, "Sheet3")
# f.save()

print(R1)
print(R2)
print(R3)

[[0.46714184 0.36618056 0.50556014 0.49314675 0.48112522 0.70888121]
 [0.58392729 0.659125   0.45500413 0.40099162 0.28867513 0.3544406 ]
 [0.42042765 0.48824074 0.53083815 0.58530189 0.67357531 0.49621684]
 [0.51385602 0.43941667 0.50556014 0.53922432 0.48112522 0.3544406 ]]
[[0.8        0.55555556 0.95238095 0.81818182 0.71428571 1.        ]
 [1.         1.         0.85714286 0.69230769 0.42857143 0.5       ]
 [0.72       0.74074074 1.         1.         1.         0.7       ]
 [0.88       0.66666667 0.95238095 0.9        0.71428571 0.5       ]]
[[0.28571429 0.         0.66666667 0.5        0.5        1.        ]
 [1.         1.         0.         0.         0.         0.        ]
 [0.         0.41666667 1.         1.         1.         0.4       ]
 [0.57142857 0.25       0.66666667 0.75       0.5        0.        ]]


## 9.2 常用的综合评价数学模型
综合评价数学模型就是将同一评价对象不同方面的多个指标值综合在一起, 得到一个整体性评价指标值的一个数学表达式. 通常根据评价的特点与需要来选择合适的综合评价数学模型. 针对 $n$ 个评价对象, $m$ 个评价指标 $x_1, x_2, \cdots, x_m$, 第 $i(i=1,2, \cdots, n)$ 个评价对象的指标值 $\boldsymbol{a}_i=\left[a_{i 1}, a_{i 2}, \cdots, a_{i m}\right]$, 经过预处理的指标值为 $b_i=\left[b_{i 1}, b_{i 2}, \cdots, b_{i m}\right]$.

### 9.2.1 线性加权综合评价模型
设指标变量的权重系数向量为 $\boldsymbol{w}=\left[w_1, w_2, \cdots, w_m\right]$, 这里的权重向量可以利用专家咨询主观赋权, 也可以利用樀权法、主成分分析法等方法得到客观权重.
线性加权综合模型是使用最普遍的一种简单综合评价模型. 其实质是在指标权重确定后, 对每个评价对象求各个指标的加权和, 即令
$$
f_i=\sum_{j=1}^m w_j b_{i j} \quad(i=1,2, \cdots, n),
$$
则 $f_i$ 就是第 $i$ 个评价对象的加权综合评价值.
线性加权模型的主要特点:
(1) 由于总的权重之和为 1 , 各指标可以线性相互补偿;
(2) 权重系数对评价结果的影响明显, 权重大的指标对综合指标作用较大;
(3) 计算简单, 可操作性强;
(4) 线性加权综合评价模型适用于各评价指标之间相互独立的情况, 若 $m$ 个评价指标不完全独立, 其结果将导致各指标间信息的重复起作用, 使评价结果不能客观地反映实际.

### 9.2.2 TOPSIS 法
TOPSIS 法是理想解的排序方法 (technique for order preference by similarity to ideal solution) 的英文缩写. 它借助于评价问题的正理想解和负理想解, 对各评价对象进行排序. 所谓正理想解是一个虚拟的最佳对象, 其每个指标值都是所有评价对象中该指标的最好值; 而负理想解则是另一个虚拟的最差对象, 其每个指标值都是所有评价对象中该指标的最差值. 求出各评价对象与正理想解和负理想解的距离, 并以此对各评价对象进行优劣排序.
设综合评价问题含有 $n$ 个评价对象、 $m$ 个指标, 相应的指标观测值分别为
$$
a_{i j} \quad(i=1,2, \cdots, n ; j=1,2, \cdots, m),
$$
则 TOPSIS 法的计算过程如下:
(1) 将评价指标进行预处理, 即进行一致化 (全部化为极大型指标) 和无量纲化, 并构造评价矩阵 $\boldsymbol{B}=\left(b_{i j}\right)_{n \times m}$.
(2) 确定正理想解 $C^{+}$和负理想解 $C^{-}$.
设正理想解 $C^{+}$的第 $j$ 个属性值为 $c_j^{+}$, 即 $C^{+}=\left[c_1^{+}, c_2^{+}, \cdots, c_m^{+}\right]$; 负理想解 $C^{-}$的第 $j$ 个属性值为 $c_j^{-}$, 即 $C^{-}=\left[c_1^{-}, c_2^{-}, \cdots, c_m^{-}\right]$, 则
$$
\begin{aligned}
& c_j^{+}=\max _{1 \leqslant i \leqslant n} b_{i j}, \quad j=1,2, \cdots, m, \\
& c_j^{-}=\min _{1 \leqslant i \leqslant n} b_{i j}, \quad j=1,2, \cdots, m .
\end{aligned}
$$
(3) 计算各评价对象到正理想解及到负理想解的距离.
各评价对象到正理想解的距离为
$$
s_i^{+}=\sqrt{\sum_{j=1}^m\left(b_{i j}-c_j^{+}\right)^2}, \quad i=1,2, \cdots, n .
$$
各评价对象到负理想解的距离为
$$
s_i^{-}=\sqrt{\sum_{j=1}^m\left(b_{i j}-c_j^{-}\right)^2}, \quad i=1,2, \cdots, n .
$$
(4) 计算各评价对象对理想解的相对接近度
$$
f_i=s_i^{-} /\left(s_i^{-}+s_i^{+}\right), \quad i=1,2, \cdots, n .
$$
(5) 按 $f_i$ 由大到小排列各评价对象的优劣次序.
注 9.2 若已求得指标权重向量 $\boldsymbol{w}=\left[w_1, w_2, \cdots, w_m\right]$, 则可利用评价矩阵 $\boldsymbol{B}=\left(b_{i j}\right)_{n \times m}$, 构造加权规范评价矩阵 $\tilde{\boldsymbol{B}}=\left(\tilde{b}_{i j}\right)$, 其中 $\tilde{b}_{i j}=w_j b_{i j}, i=1,2, \cdots, n$; $j=1,2, \cdots, m$.在上面的计算步骤中以 $\tilde{\boldsymbol{B}}$ 代替 $\boldsymbol{B}$ 做评价.

### 9.2.3 灰色关联度分析
设综合评价问题含有 $n$ 个评价对象、 $m$ 个指标, 相应的指标观测值分别为
$$
a_{i j} \quad(i=1,2, \cdots, n ; j=1,2, \cdots, m) .
$$
灰色关联度分析具体步骤如下:
(1) 将评价指标进行预处理, 即进行一致化 (全部化为极大型指标) 和无量纲化, 并构造评价矩阵 $\boldsymbol{B}=\left(b_{i j}\right)_{n \times m}$.
(2) 确定比较数列 (评价对象) 和参考数列 (评价标准).
比较数列为
$$
\boldsymbol{b}_i=\left\{b_{i j} \mid j=1,2, \cdots, m\right\}, \quad i=1,2, \cdots, n,
$$
即 $\boldsymbol{b}_i$ 为第 $i$ 个评价对象的标准化指标向量值.
参考数列为 $\boldsymbol{b}_0=\left\{b_{0 j} \mid j=1,2, \cdots, m\right\}$, 这里 $b_{0 j}=\max _{1 \leqslant i \leqslant n} b_{i j}, j=1,2, \cdots, m$. 即参考数列相当于一个虚拟的最好评价对象的各指标值.
(3) 计算灰色关联系数
$$
\begin{gathered}
\xi_{i j}=\frac{\min _{1 \leqslant s \leqslant n} \min _{1 \leqslant k \leqslant m}\left|b_{0 k}-b_{s k}\right|+\rho \max _{1 \leqslant s \leqslant n} \max _{1 \leqslant k \leqslant m}\left|b_{0 k}-b_{s k}\right|}{\left|b_{0 j}-b_{i j}\right|+\rho \max _{1 \leqslant s \leqslant n} \max _{1 \leqslant k \leqslant m}\left|b_{0 k}-b_{s k}\right|}, \\
i=1,2, \cdots, n, \quad j=1,2, \cdots, m .
\end{gathered}
$$
$\xi_{i j}$ 为比较数列 $\boldsymbol{b}_i$ 对参考数列 $\boldsymbol{b}_0$ 在第 $j$ 个指标上的关联系数, 其中 $\rho \in[0,1]$ 为分辨系数. 称式中 $\min _{1 \leqslant s \leqslant n} \min _{1 \leqslant k \leqslant m}\left|b_{0 k}-b_{s k}\right|, \max _{1 \leqslant s \leqslant n} \max _{1 \leqslant k \leqslant m}\left|b_{0 k}-b_{s k}\right|$ 分别为两级最小差及两级最大差.
一般来讲, 分辨系数 $\rho$ 越大, 分辨率越大; $\rho$ 越小, 分辨率越小.
(4) 计算灰色关联度.
灰色关联度的计算公式为
$$
r_i=\sum_{j=1}^m w_j \xi_{i j}, \quad i=1,2, \cdots, n .
$$
其中 $w_j$ 为第 $j$ 个指标变量 $x_j$ 的权重, 若权重没有确定, 各指标变量也可以取等权重, 即 $w_j=1 / m, r_i$ 为第 $i$ 个评价对象对理想对象的灰色关联度.
(5) 评价分析.
根据灰色关联度的大小, 对各评价对象进行排序, 可建立评价对象的关联度, 关联度越大其评价结果越好.

### 9.2.4 熵值法
在信息论中信息熵是信息不确定性的一种度量. 一般来说, 信息量越大, 樀值越小, 信息的效用值越大; 反之, 信息量越小, 熵值越大, 信息的效用值越小. 而熵值法就是通过计算各指标观测值的信息熵, 根据各指标的相对变化程度对系统整体的影响来确定指标权重系数的一种赋权方法. 熵值法的计算过程如下.
(1) 计算在第 $j$ 项指标下第 $i$ 个评价对象的特征比重.
设第 $i$ 个评价对象的第 $j$ 个观测值的标准化数据 $b_{i j}>0(i=1,2, \cdots, n ; j=$ $1,2, \cdots, m)$, 则在第 $j$ 项指标下第 $i$ 个评价对象的特征比重为
$$
p_{i j}=\frac{b_{i j}}{\sum_{i=1}^n b_{i j}}(i=1,2, \cdots, n ; j=1,2, \cdots, m) .
$$
(2) 计算第 $j$ 项指标的熵值为
$$
e_j=-\frac{1}{\ln n} \sum_{i=1}^n p_{i j} \ln p_{i j} \quad(j=1,2, \cdots, m),
$$
不难看出, 如果第 $j$ 项指标的观测值差异越大, 熵值越小; 反之, 熵值越大.
(3) 计算第 $j$ 项指标的差异系数为
$$
g_j=1-e_j \quad(j=1,2, \cdots, m) .
$$
如果第 $j$ 项指标的观测值差异越大, 则差异系数 $g_j$ 就越大, 第 $j$ 项指标也就越重要.
(4) 确定第 $j$ 项指标的权重系数
$$
w_j=\frac{g_j}{\sum_{k=1}^m g_k}(j=1,2, \cdots, m) .
$$
(5) 计算第 $i$ 个评价对象的综合评价值
$$
f_i=\sum_{j=1}^m w_j p_{i j},
$$
评价值越大越好.

### 9.2.5 秩和比法
秩和比 (rank sum ratio, RSR) 综合评价法的基本原理是在一个 $n$ 行 $m$ 列矩阵 中, 通过秩转换, 获得无量纲统计量 RSR; 以 RSR 值对评价对象的优劣直接排序, 从而对评价对象做出综合评价.
先介绍一下样本秩的概念.
定义 9.1 (样本秩) 设 $c_1, c_2, \cdots, c_n$ 是从一元总体抽取的容量为 $n$ 的样本, 其从小到大的顺序统计量是 $c_{(1)}, c_{(2)}, \cdots, c_{(n)}$. 若 $c_i=c_{(k)}$, 则称 $k$ 是 $c_i$ 在样本中的秩, 记作 $R_i$, 对每一个 $i=1,2, \cdots, n$, 称 $R_i$ 是第 $i$ 个秩统计量. $R_1, R_2, \cdots, R_n$ 总称为秩统计量.
例如, 对样本数据
$$
-0.8,-3.1,1.1,-5.2,4.2,
$$
顺序统计量是
$$
-5.2,-3.1,-0.8,1.1,4.2,
$$
而秩统计量是
$$
3,2,4,1,5 \text {. }
$$
设综合评价问题含有 $n$ 个评价对象 $m$ 个指标, 相应的指标观测值分别为 $a_{i j}$, $i=1,2, \cdots, n ; j=1,2, \cdots, m$, 构造数据矩阵 $\boldsymbol{A}=\left(a_{i j}\right)_{n \times m}$.
秩和比综合评价法的步骤如下.
(1) 编秩.
对数据矩阵 $\boldsymbol{A}=\left(a_{i j}\right)_{n \times m}$ 逐列编秩, 即分别编出每个指标值的秩, 其中极大型指标从小到大编秩, 极小型指标从大到小编秩, 指标值相同时编平均秩, 得到的秩矩阵记为 $\boldsymbol{R}=\left(R_{i j}\right)_{n \times m}$.
(2) 计算秩和比 (RSR).
如果各评价指标权重相同, 根据公式
$$
\mathrm{RSR}_i=\frac{1}{m n} \sum_{j=1}^m R_{i j}, \quad i=1,2, \cdots, n,
$$
计算秩和比. 当各评价指标的权重不同时, 计算加权秩和比, 其计算公式为
$$
\mathrm{RSR}_i=\frac{1}{n} \sum_{j=1}^m w_j R_{i j}, \quad i=1,2, \cdots, n,
$$
其中 $w_j$ 为第 $j$ 个评价指标的权重, $\sum_{j=1}^m w_j=1$.
(3) 秩和比排序.
根据秩和比 $\operatorname{RSR}_i(i=1,2, \cdots, n)$ 对各评价对象进行排序, 秩和比越大其评价结果越好.

### 9.2.6 综合评价示例
例 9.2 (续例 9.1) 采用比例变换法得到的评价矩阵
$$
\boldsymbol{R}_2=\left[\begin{array}{cccccc}
0.8 & 0.5556 & 0.9524 & 0.8182 & 0.7143 & 1 \\
1 & 1 & 0.8571 & 0.6923 & 0.4286 & 0.5 \\
0.72 & 0.7407 & 1 & 1 & 1 & 0.7 \\
0.88 & 0.6667 & 0.9524 & 0.9 & 0.7143 & 0.5
\end{array}\right] .
$$
作为标准化数据矩阵 $\boldsymbol{B}=\left(b_{i j}\right)_{4 \times 6}$, 分别利用 TOPSIS 法、灰色关联度、熵值法与秩和比法对战斗机的性能进行综合评价.

1.利用 TOPSIS 法进行综合评价
(1) 确定正理想和负理想解分别为
$$
\begin{gathered}
C^{+}=[1,1,1,1,1,1], \\
C^{-}=[0.72,0.5556,0.8571,0.6923,0.4286,0.5] .
\end{gathered}
$$
(2) 由计算公式
$$
s_i^{+}=\sqrt{\sum_{j=1}^6\left(b_{i j}-c_j^{+}\right)^2}, \quad s_i^{-}=\sqrt{\sum_{j=1}^6\left(b_{i j}-c_j^{-}\right)^2}, \quad i=1,2,3,4,
$$
计算各评价对象到正理想解和负理想解的距离分别为
$$
\begin{aligned}
& \boldsymbol{s}^{+}=[0.5954,0.8316,0.4854,0.6851], \\
& \boldsymbol{s}^{-}=[0.6025,0.5253,0.7183,0.4145] .
\end{aligned}
$$
(3) 由公式
$$
f_i=s_i^{-} /\left(s_i^{-}+s_i^{+}\right), \quad i=1,2,3,4 .
$$
计算各机型对理想解的相对接近度为
$$
\boldsymbol{F}=\left[f_1, f_2, f_3, f_4\right]=[0.5029,0.3871,0.5967,0.3769] .
$$
(4) 根据相对接近度对各机型按优劣次序排序如下
$$
A_3>A_1>A_2>A_4 .
$$

2.灰色关联度评价
(1) 灰色关联度的计算数据如表 9.5 所示.
表 9.5 灰色关联系数及关联度计算数据
\begin{array}{cccccccc}
\hline & 最大速度 x_1 & 飞行半径 x_2 & 最大负载 x_3 & 费用 x_4 & 可靠性 x_5 & 灵敏度 x_6 & r_i \\
\hline
A_1 & 0.5882 & 0.3913 & 0.8571 & 0.6111 & 0.5 & 1 & 0.6580 \\
A_2 & 1 & 1 & 0.6667 & 0.4815 & 0.3333 & 0.3636 & 0.6409 \\
A_3 & 0.5051 & 0.5243 & 1 & 1 & 1 & 0.4878 & 0.7529 \\
A_4 & 0.7042 & 0.4615 & 0.8571 & 0.7407 & 0.5 & 0.3636 & 0.6045 \\
\hline
\end{array}
(2) 根据灰色关联度对各机型按优劣次序排序如下
$$
A_3>A_1>A_2>A_4 .
$$

3.煵值法
(1) 利用公式
$$
p_{i j}=\frac{b_{i j}}{\sum_{i=1}^4 b_{i j}}(i=1,2,3,4 ; j=1,2, \cdots, 6) .
$$
求各指标的特征比重为
$$
\boldsymbol{P}=\left[\begin{array}{cccccc}
0.2353 & 0.1875 & 0.2532 & 0.2399 & 0.25 & 0.3704 \\
0.2941 & 0.3375 & 0.2278 & 0.2030 & 0.15 & 0.1852 \\
0.2118 & 0.25 & 0.2658 & 0.2932 & 0.35 & 0.2593 \\
0.2588 & 0.225 & 0.2532 & 0.2639 & 0.25 & 0.1852
\end{array}\right] .
$$
(2) 利用公式
$$
e_j=-\frac{1}{\ln 4} \sum_{i=1}^4 p_{i j} \ln p_{i j} \quad(j=1,2, \cdots, 6),
$$
计算各指标的熵值为
$$
e=\left[e_1, e_2, \cdots, e_6\right]=[0.9947,0.9829,0.9989,0.9936,0.9703,0.9684] .
$$
(3) 利用公式
$$
g_j=1-e_j \quad(j=1,2, \cdots, 6),
$$
计算各指标的差异系数为
$$
\boldsymbol{g}=\left[g_1, g_2, \cdots, g_6\right]=[0.0053,0.0171,0.0011,0.0064,0.0297,0.0316] .
$$
(4) 由公式
$$
w_j=\frac{g_j}{\sum_{k=1}^6 g_k} \quad(j=1,2, \cdots, 6)
$$
求得各指标的权重向量为
$$
\boldsymbol{W}_2=\left[w_1, w_2, \cdots, w_6\right]=[0.0583,0.1870,0.0122,0.0700,0.3255,0.3470] .
$$
(5) 计算第 $i$ 个评价对象的综合评价值
$$
f_i=\sum_{j=1}^6 w_j p_{i j}, \quad i=1,2,3,4,
$$
得 4 个评价对象的评价值向量
$$
\boldsymbol{F}=\left[f_1, f_2, f_3, f_4\right]=[0.2785,0.2103,0.2868,0.2244],
$$
各机型按优劣次序排序如下
$$
A_3>A_1>A_4>A_2 .
$$

4.利用秩和比法进行综合评价
1)编秩
对于各机型的评价指标进行编秩, 结果如表 9.6 所示.
表 9.6 各机型指标值的编秩值
\begin{array}{ccccccc}
\hline & 最大速度 x_1 & 飞行半径 x_2 & 最大负载 x_3 & 费用 x_4 & 可靠性 x_5 & 灵敏度 x_6 \\
\hline
A_1 & 2 & 1 & 2.5 & 2 & 2.5 & 4 \\
A_2 & 4 & 4 & 1 & 1 & 1 & 1.5 \\
A_3 & 1 & 3 & 4 & 4 & 4 & 3 \\
A_4 & 3 & 2 & 2.5 & 3 & 2.5 & 1.5 \\
\hline
\end{array}
2)计算秩和比
用公式 $\operatorname{RSR}_i=\sum_{j=1}^6 w_j R_{i j} / 4, i=1,2,3,4$, 这里取 $w_j=\frac{1}{6}(j=1,2, \cdots, 6)$, 计 算加权秩和比为
$$
\mathbf{R S R}=[0.5833,0.5208,0.7917,0.6042] .
$$
3)秩和比排序
根据 $\operatorname{RSR}_i(i=1,2,3,4)$ 对 4 种机型的性能按优劣次序排序为
$$
A_3>A_4>A_1>A_2 .
$$

上述 4 种评价方法的 Python 程序如下:

### 9.2.7 代码：Topsis方法、灰色关联方法、Etropy方法、秩和方法

In [ ]:
import numpy as np
from scipy.stats import rankdata
import os

a = np.loadtxt(os.path.join("data","Pdata9_1_3.txt"))

In [ ]:
###################### Topsis方法#################
cplus = a.max(axis=0)   #逐列求最大值
cminus = a.min(axis=0)  #逐列求最小值
print("正理想解=",cplus,"负理想解=",cminus)


d1 = np.linalg.norm(a-cplus, axis=1)  #求到正理想解的距离
d2 = np.linalg.norm(a-cminus, axis=1) #求到负理想解的距离
print(d1, d2)   #显示到正理想解和负理想解的距离
f1 = d2/(d1+d2); print("TOPSIS的评价值为：", f1)


正理想解= [1. 1. 1. 1. 1. 1.] 负理想解= [0.72       0.55555556 0.85714286 0.69230769 0.42857143 0.5       ]
[0.59538974 0.83163293 0.48540227 0.685136  ] [0.60245103 0.52529122 0.71826658 0.4144692 ]
TOPSIS的评价值为： [0.50294751 0.38711907 0.59673105 0.37692547]


In [ ]:
###################### 灰色关联方法#################
t = cplus-a   #计算参考序列与每个序列的差
mmin = t.min(); mmax=t.max()  #计算最小差和最大差
rho = 0.5  #分辨系数
xs = (mmin+rho*mmax)/(t+rho*mmax)  #计算灰色关联系数
f2  =  xs.mean(axis=1)  #求每一行的均值
print("\n关联系数=", xs,'\n关联度=',f2)  #显示灰色关联系数和灰色关联度


关联系数= [[0.58823529 0.39130435 0.85714286 0.61111111 0.5        1.        ]
 [1.         1.         0.66666667 0.48148148 0.33333333 0.36363636]
 [0.50505051 0.52427184 1.         1.         1.         0.48780488]
 [0.70422535 0.46153846 0.85714286 0.74074074 0.5        0.36363636]] 
关联度= [0.6579656  0.64085297 0.75285454 0.6045473 ]


In [ ]:
###################### Etropy方法#################
[n, m]=a.shape
cs=a.sum(axis=0)  #逐列求和
P=1/cs*a   #求特征比重矩阵
e=-(P*np.log(P)).sum(axis=0)/np.log(n)  #计算熵值
g=1-e   #计算差异系数
w = g / sum(g)  #计算权重
F = P @ w       #计算各对象的评价值
print("\nP={}\n,e={}\n,g={}\n,w={}\nF={}".format(P,e,g,w,F))


P=[[0.23529412 0.1875     0.25316456 0.23990158 0.25       0.37037037]
 [0.29411765 0.3375     0.2278481  0.20299364 0.15       0.18518519]
 [0.21176471 0.25       0.26582278 0.29321304 0.35       0.25925926]
 [0.25882353 0.225      0.25316456 0.26389174 0.25       0.18518519]]
,e=[0.99468893 0.98294821 0.99888759 0.9936177  0.97032272 0.96836882]
,g=[0.00531107 0.01705179 0.00111241 0.0063823  0.02967728 0.03163118]
,w=[0.05825717 0.18704101 0.01220201 0.07000746 0.32552998 0.34696237]
F=[0.27854885 0.21033387 0.28675644 0.22436085]


In [ ]:
###################### 秩和方法#################
R=[rankdata(a[:,i]) for i in np.arange(6)]  #求每一列的秩
R=np.array(R).T   #构造秩矩阵
print("\n秩矩阵为：\n",R)
RSR=R.mean(axis=1)/n; print("RSR=", RSR)


秩矩阵为：
 [[2.  1.  2.5 2.  2.5 4. ]
 [4.  4.  1.  1.  1.  1.5]
 [1.  3.  4.  4.  4.  3. ]
 [3.  2.  2.5 3.  2.5 1.5]]
RSR= [0.58333333 0.52083333 0.79166667 0.60416667]


## 9.3 层次分析法

### 9.3.1 案例

1.问题提出
春天来了, 张勇、李雨、王刚、赵宇四位大学生相约去寻找那生机勃勃、盎然向上的春天, 去呼吸那沈人心脾的春天的气息. “五一” 长假终于到了, 但他们却发生了争执. 原来张勇想到风光绮丽的苏杭去看园林的春色, 李雨却想到风景迷人的黄山去看姏峨挺拔的黄山松, 王刚则想到风光秀丽的庐山去寻找庐山的真面目. 三个人争得面红耳赤, 只有赵宇坐在一旁手里拿着笔, 不停地写着, 最后站起来说: “别吵了, 我计算过了, 去苏杭是明智的选择. ”说着他拿起笔在纸上画了一张分析图 (图 9.1), 并讲解起来.
图 9.1 最佳旅游地选择的层次结构图
![](images/最佳旅游地选择的层次结构图.png)

2.问题分析
图 9.1 是一个递阶层次结构, 它分三个层次, 第一层 (选择最佳旅游地) 称之为目标层; 第二层 (旅游的倾向) 称之为准则层; 第三层 (旅游地点) 称之为方案层. 各层之间的联系用相连的直线表示. 要依据喜好对这三个层次相互比较判断进行综合, 在三个旅游地中确定哪一个为最佳地点.

3.模型建立与求解
具体的做法是通过相互比较, 假设各准则对目标的权重和各方案对每一准则的权重. 首先在准则层对目标层进行赋权, 认为费用应占最大的比重 (因为是学生), 其次是景色 (目的主要是旅游), 再者是旅途, 至于吃住对年轻人来说不太重要. 表 9.7 是采用两两比较判断法得到的数据.
表 9.7 旅游决策准则层对目标层的两两比较表
\begin{array}{cccccc}
\hline 项目 & 景色 & 费用 & 饮食 & 居住 & 旅途 \\
\hline 最色 & 1 & $1 / 2$ & 5 & 5 & 3 \\
專用 & 2 & 1 & 7 & 7 & 5 \\
饮食 & $1 / 5$ & $1 / 7$ & 1 & $1 / 2$ & $1 / 3$ \\
居住 & $1 / 5$ & $1 / 7$ & 2 & 1 & $1 / 2$ \\
旅途 & $1 / 3$ & $1 / 5$ & 3 & 2 & 1 \\
\hline
\end{array}
把表 9.7 中的数据用矩阵 $\boldsymbol{A}=\left(a_{i j}\right)_{5 \times 5}$ 表示, 则
$$
\boldsymbol{A}=\left[\begin{array}{ccccc}
1 & 1 / 2 & 5 & 5 & 3 \\
2 & 1 & 7 & 7 & 5 \\
1 / 5 & 1 / 7 & 1 & \frac{1}{2} & \frac{1}{3} \\
1 / 5 & 1 / 7 & 2 & 1 & \frac{1}{2} \\
1 / 3 & 1 / 5 & 3 & 2 & 1
\end{array}\right]
$$
比较判断矩阵 $\boldsymbol{A}$ 也称之为正互反矩阵. $n$ 阶正互反矩阵 $\boldsymbol{B}=\left(b_{i j}\right)_{n \times n}$ 的特点是
$$
b_{i j}>0, \quad b_{j i}=\frac{1}{b_{i j}}, \quad b_{i i}=1, \quad i, j=1,2, \cdots, n .
$$
矩阵 $A$ 中 $a_{12}=\frac{1}{2}$, 表示景色与费用对选择旅游地这个目标来说的重要之比为 $1: 2$ (景色比费用稍微不重要), 而 $a_{21}=2$ 则表示费用与景色对选择旅游地这个目标来说的重要之比为 $2: 1$ (费用比景色稍微重要); $a_{13}=5$ 表示景色与饮食对旅游地这个目标来说的重要之比为 $5: 1$ (景色比饮食明显重要), 而 $a_{31}=\frac{1}{5}$ 则表示饮食与景色对选择旅游地这个目标来说的重要之比为 1:5 (饮食比景色明显不重要); $a_{23}=7$ 表示费用与饮食对选择旅游地这个目标来说的重要之比为 $7: 1$ (费用 比饮食强烈重要), 而 $a_{32}=\frac{1}{7}$ 则表示饮食与费用对选择旅游地这个目标来说的重要之比为 1:7 (饮食比景色强烈不重要). 由此可见, 在进行两两比较时, 只需要进行 $4+3+2+1=10$ 次比较即可.
现在的问题是怎样由正互反矩阵确定诸因素对目标层的权重. 由于 $\boldsymbol{A}$ 是正矩 阵, 由 Perron(佩罗) 定理知, 正互反矩阵一定存在一个最大的特征值 $\lambda_{\max }$, 并且 $\lambda_{\max }$ 所对应的特征向量 $\boldsymbol{X}$ 为正向量, 即 $\boldsymbol{A X}=\lambda_{\max } \boldsymbol{X}$, 将 $\boldsymbol{X}$ 归一化 (各个分量之和等于 1) 作为权向量 $\boldsymbol{W}$, 即 $\boldsymbol{W}$ 满足 $\boldsymbol{A W}=\lambda_{\max } \boldsymbol{W}$.
利用 Python 可以求出最大特征值 $\lambda_{\max }=5.0976$, 对应的特征向量经归一化得
$$
\boldsymbol{W}=[0.2863,0.4809,0.0485,0.0685,0.1157]^{\mathrm{T}},
$$
就是准则层对目标层的排序向量. 用同样的方法, 给出第三层 (方案层) 对第二层 (准则层) 的每一准则比较判断矩阵, 由此求出各排序向量 (最大特征值所对应的特 征向量归一化).
$$
\boldsymbol{B}_1 \text { (景色) }=\left[\begin{array}{ccc}
1 & 1 / 3 & 1 / 2 \\
3 & 1 & 1 / 2 \\
2 & 2 & 1
\end{array}\right], \quad \boldsymbol{P}_1=\left[\begin{array}{l}
0.1677 \\
0.3487 \\
0.4836
\end{array}\right],
$$
$$
\begin{aligned}
& \boldsymbol{B}_2(\text { 费用 })=\left[\begin{array}{ccc}
1 & 3 & 2 \\
1 / 3 & 1 & 2 \\
1 / 2 & 1 / 2 & 1
\end{array}\right], \quad \boldsymbol{P}_2=\left[\begin{array}{l}
0.5472 \\
0.2631 \\
0.1897
\end{array}\right] \text {, } \\
& \boldsymbol{B}_3(\text { 饮食 })=\left[\begin{array}{ccc}
1 & 4 & 3 \\
1 / 4 & 1 & 2 \\
1 / 3 & 1 / 2 & 1
\end{array}\right], \quad \boldsymbol{P}_3=\left[\begin{array}{l}
0.6301 \\
0.2184 \\
0.1515
\end{array}\right] \text {, } \\
& \boldsymbol{B}_4(\text { 居住 })=\left[\begin{array}{ccc}
1 & 3 & 2 \\
1 / 3 & 1 & 2 \\
1 / 2 & 1 / 2 & 1
\end{array}\right], \quad \boldsymbol{P}_4=\left[\begin{array}{c}
0.5472 \\
0.2631 \\
0.1897
\end{array}\right] \text {, } \\
& \boldsymbol{B}_5(\text { 旅途 })=\left[\begin{array}{ccc}
1 & 2 & 3 \\
1 / 2 & 1 & 1 / 2 \\
1 / 3 & 2 & 1
\end{array}\right], \quad \boldsymbol{P}_5=\left[\begin{array}{c}
0.5472 \\
0.1897 \\
0.2631
\end{array}\right] . \\
&
\end{aligned}
$$
最后, 将由各准则对目标的权向量 $\boldsymbol{W}$ 和各方案对每一准则的权向量, 计算各方案对目标的权向量, 称为组合权向量.
若记
$$
\boldsymbol{P}=\left[\boldsymbol{P}_1, \boldsymbol{P}_2, \boldsymbol{P}_3, \boldsymbol{P}_4, \boldsymbol{P}_5\right]=\left[\begin{array}{lllll}
0.1677 & 0.5472 & 0.6301 & 0.5472 & 0.5472 \\
0.3487 & 0.2631 & 0.2184 & 0.2631 & 0.1897 \\
0.4836 & 0.1897 & 0.1515 & 0.1897 & 0.2631
\end{array}\right],
$$
则根据矩阵乘法, 可得组合权向量
$$
\boldsymbol{K}=\left[\begin{array}{l}
k_1 \\
k_2 \\
k_3
\end{array}\right]=\boldsymbol{P W}=\left[\begin{array}{l}
0.4426 \\
0.2769 \\
0.2805
\end{array}\right] .
$$

4.模型的一致性检验
如果一个正互反矩阵 $\boldsymbol{A}=\left(a_{i j}\right)_{n \times n}$ 满足
$$
a_{i j} a_{j k}=a_{i k}, \quad i, j, k=1,2, \cdots, n,
$$
则称 $\boldsymbol{A}$ 为一致性判断矩阵, 简称一致阵.
通过两两成对比较得到的判断矩阵 $\boldsymbol{A}$ 不一定满足矩阵的一致性条件 (9.2), 我们希望能找到一个数量标准来衡量矩阵 $\boldsymbol{A}$ 不一致的程度.
关于正互反矩阵 $\boldsymbol{A}$, 根据矩阵论的 Perron-Frobenius 定理, 有下面的结论.

定理 9.1 正互反矩阵 $\boldsymbol{A}$ 存在正实数的按模最大的特征值, 这个特征值是单值, 其余的特征值的模均小于它, 并且这个最大特征值对应着正的特征向量.

定理 9.2 $n$ 阶正互反矩阵 $\boldsymbol{A}=\left(a_{i j}\right)_{n \times n}$ 是一致阵当且仅当其最大特征值 $\lambda_{\max }=n$.

根据定理 9.2, 就可以检验判断矩阵是否具有一致性, 如果判断矩阵不具有一致性, 则 $\lambda_{\max } \neq n$, 并且这时的特征向量 $\boldsymbol{W}$ 就不能真实反映各指标的权重. 衡量不一致程度的数量指标称为一致性指标, Saaty 将它定义为
$$
\mathrm{CI}=\frac{\lambda_{\max }-n}{n-1} .
$$
由于矩阵 $\boldsymbol{A}$ 的所有特征值的和 $\sum_{i=1}^n \lambda_i=n$, 实际上 $\mathrm{CI}$ 是 $n-1$ 个特征值 $\lambda_2, \lambda_3, \cdots$, $\lambda_n$ (最大特征值 $\lambda_{\max }$ 除外) 的平均值的相反数. 当然对于一致性正互反阵来说, 一致性指标 CI 等于零.
显然, 仅依靠 CI 值来作为判断矩阵 $A$ 是否具有满意一致性的标准是不够的, 因为客观事物的复杂性和人们认识的多样性, 以及可能产生的片面性与问题的因素多少、规模大小有关, 即随着 $n$ 值 (1 9) 的增大, 误差相应也会增大, 为此, Saaty 又提出了平均随机一致性指标 RI.
平均随机一致性指标 RI 是这样得到的: 对于固定的 $n$, 随机构造正互反矩阵 $\boldsymbol{A}^{\prime}=\left(a_{i j}^{\prime}\right)_{n \times n}$, 其中 $a_{i j}^{\prime}$ 是从 $1,2, \cdots, 9, \frac{1}{2}, \frac{1}{3}, \cdots, \frac{1}{9}$ 中随机抽取的, 这样的 $\boldsymbol{A}^{\prime}$ 是最不一致的, 取充分大的子样本 (500个样本) 得到 $\boldsymbol{A}^{\prime}$ 的最大特征值的平均值 $\lambda_{\max }^{\prime}$, 定义
$$
\mathrm{RI}=\frac{\lambda_{\max }^{\prime}-n}{n-1} .
$$
对于 1-9 阶的判断矩阵, Saaty 给出 RI 值, 如表 9.8 所示.
表 9.8 平均随机一致性指标 RI
\begin{array}{cccccccccc}
\hline n & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 \\
\hline RI & 0 & 0 & 0.58 & 0.90 & 1.12 & 1.24 & 1.32 & 1.41 & 1.45 \\
\hline
\end{array}
令 $\mathrm{CR}=\mathrm{CI} / \mathrm{RI}, \mathrm{CR}$ 为一致性比率, 当 $\mathrm{CR}<0.1$ 时, 认为判断矩阵具有满意的一致性, 否则就需要调整判断矩阵, 使之具有满意的一致性.
在上述模型中矩阵 $\boldsymbol{A}$ 的一致性比率 $\mathrm{CR}=0.0218<0.1$, 通过了一致性检验. 对于其他判断矩阵的一致性检验和总体一致性检验, 这里就省略了.

计算的 python 程序如下:

### 9.3.2 代码：层次分析法

In [ ]:
from scipy.sparse.linalg import eigs
from numpy import array, hstack
a = array([
    [  1, 1/2, 5,   5,   3],
    [  2,   1, 7,   7,   5],
    [1/5, 1/7, 1, 1/2, 1/3],
    [1/5, 1/7, 2,   1, 1/2],
    [1/3, 1/5, 3,   2,   1]
])
L, V = eigs(a, 1)

CR = (L-5)/4/1.12  #计算矩阵A的一致性比率
W = V/sum(V)
print("最大特征值为：", L)

print("最大特征值对应的特征向量W=\n", W)
print("CR=", CR)

B1 =array([
    [1, 1/3, 1/2],
    [3,   1, 1/2],
    [2,   2,   1]
])
L1, P1 = eigs(B1, 1)
P1 = P1/sum(P1)
print("P1=", P1)

B2 = array([
    [  1,  3, 2],
    [1/3,  1, 2],
    [1/2,1/2, 1]
])
t2, P2 = eigs(B2, 1)
P2 = P2/sum(P2)

print("P2=", P2)
B3 = array([
    [  1,   4, 3],
    [1/4,   1, 2],
    [1/3, 1/2, 1]
])
t3, P3 = eigs(B3, 1)
P3 = P3/sum(P3)
print("P3=", P3)

B4 = array([
    [  1,   3, 2],
    [1/3,   1, 2],
    [1/2, 1/2, 1]
])
t4, P4 = eigs(B4, 1)
P4 = P4/sum(P4)
print("P4=", P4)

B5 = array([
    [  1, 2,   3],
    [1/2, 1, 1/2],
    [1/3, 2,   1]
])
t5, P5 = eigs(B5, 1)
P5 = P5/sum(P5)
print("P5=", P5)

K = hstack([P1, P2, P3, P4, P5])@W  #矩阵乘法
print("K=", K)

最大特征值为： [5.09758844+0.j]
最大特征值对应的特征向量W=
 [[0.28626525-0.j]
 [0.48093287-0.j]
 [0.04851865-0.j]
 [0.0685439 -0.j]
 [0.11573932-0.j]]
CR= [0.02178313+0.j]
P1= [[0.16765631-0.j]
 [0.34873919-0.j]
 [0.4836045 -0.j]]
P2= [[0.54721643-0.j]
 [0.26307422-0.j]
 [0.18970934-0.j]]
P3= [[0.63009766-0.j]
 [0.21844266-0.j]
 [0.15145968-0.j]]
P4= [[0.54721643+0.j]
 [0.26307422+0.j]
 [0.18970934+0.j]]
P5= [[0.54721643-0.j]
 [0.18970934-0.j]
 [0.26307422-0.j]]
K= [[0.44258285+0.j]
 [0.27694046+0.j]
 [0.28047669+0.j]]


5.结果分析
上述结果表明: 方案 1 (苏杭) 在旅游选择中占的权重为 0.4426 , 接近 0.5 , 远大于方案 2 (黄山权重为 0.2769 )、方案 3 (庐山权重为 0.2805 ), 因此他们应该去苏杭.
以上分析方法称为 “层次分析法” (analytic hierarchy process, AHP) 是一种现代管理决策方法, 由美国运筹学家 T. L. Saaty 提出, 它的应用比较广泛, 遍及经济计划与管理、能源政策与分配、行为科学、军事指挥、运输、农业、教育、环境、人才等诸多领域, 如大学生的择业决策、科技人员要选择研究课题、医生要为疑难病确定治疗方案、经理要从若干个应试者中挑选秘书等, 都可用这种方法, 其特点是将定性分析用定量方法来解决.